monitor=HDMI-A-1,1920x1080@60,0x0,1
monitor=DP-1,1920x1080@60,-1080x0,1,transform,1

plugin {
  hyprfocus {
    enabled = yes
    focus_animation = shrink
    animate_floating = yes
    animate_workspacechange = yes
    shrink {
      shrink_percentage = 0.995
      in_bezier = 0.25 0.1 0.25 1
      in_speed = 2
      out_bezier = 0.25 0.1 0.25 1
      out_speed = 2
    }
  }
}
